# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26f5496c7322b4c33380889a1cb105c2bc5d204c0ef48cea73e7ad002322badfa4bb3aa9602897e42e5c7e2ac11570c4f5091e1fb0c9950f1aef9ae77cf20112

test:
  secret_key_base: bfa01282e3256c11af32e6d46eed735cd499f089441108a98bc018dfff7f5d30a3cbe917a026412ddb186152f90ff39f8222ada8a1812afedaf5b05fa2e20576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
